---
title: "Letterboxd"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
vertical_layout: scroll
editor_options: 
  chunk_output_type: console
runtime: shiny
---
  

```{r setup, include = FALSE}
suppressPackageStartupMessages({
    library(flexdashboard)
    library(tidyverse)
    library(lubridate)
    library(shiny)
    library(xml2)
    library(httr2)
    library(plotly)
    library(zoo)
    library(rvest)    
})

readRenviron('.Renviron')
print(Sys.getenv('DROPBOX_KEY'))

## New dropbox authentication process
print(str_c('Checking system variables: ', Sys.getenv('DROPBOX_KEY')))
dropboxClient <- oauth_client(
    id = Sys.getenv('DROPBOX_KEY'),
    secret = Sys.getenv('DROPBOX_SECRET'),
    token_url = "https://api.dropboxapi.com/oauth2/token",
    name = 'Rstudio_TC'
)

# dropboxToken <- oauth_flow_auth_code(
#     dropboxClient, port = 43451,
#     auth_url = "https://www.dropbox.com/oauth2/authorize?token_access_type=offline"
# )
# saveRDS(dropboxToken, 'dropbox.RDS')
dropboxToken <- readRDS('dropbox.RDS')

testing <- F

if (!testing) {
    
    ## Download letterboxd diary from dropbox
  reqDownload <-  request("https://content.dropboxapi.com/2/files/download") %>% 
            req_oauth_refresh(client = dropboxClient, 
                              refresh_token = dropboxToken$refresh_token) %>% 
            req_method('POST') %>%
            req_headers(
                'Dropbox-API-Arg' = str_c('{',
                                          '"path":"/R/trakt/letterboxd/diary.csv"',
                                          '}')
            )
        
        respDownload <- req_perform(reqDownload,
                                    path = 'diary.csv')
        
        ## Then do the same for goodreads
    reqDownload <-  request("https://content.dropboxapi.com/2/files/download") %>% 
            req_oauth_refresh(client = dropboxClient, 
                              refresh_token = dropboxToken$refresh_token) %>% 
            req_method('POST') %>%
            req_headers(
                'Dropbox-API-Arg' = str_c('{',
                                          '"path":"/R/goodreads/goodreads.csv"',
                                          '}')
            )
        
        respDownload <- req_perform(reqDownload,
                                    path = 'goodreads.csv')
}

diary <- readr::read_csv('diary.csv', show_col_types = FALSE) %>% 
    select(title = Name, date = `Watched Date`, rating = Rating, tags = Tags) %>%
    arrange(desc(date))

goodreads <- readr::read_csv('goodreads.csv', show_col_types = FALSE) %>%
    mutate(date_started= lubridate::ymd(date_started),
           date_finished =lubridate::ymd(date_finished))



## And get any new films from the RSS feed
letFeed <- xml2::read_xml("https://letterboxd.com/tomcopple/rss/") %>% 
  xml2::xml_find_all('//item') %>% 
  xml2::as_list() %>% 
  map_df(unlist) %>% 
  select(title = filmTitle, date = watchedDate, rating = memberRating) %>% 
  mutate(date = lubridate::ymd(date),
         rating = as.numeric(rating), 
         tags = "") %>% 
  filter(!is.na(date)) %>% 
  arrange(desc(date)) %>% 
  anti_join(diary, by = c('title', 'date', 'rating'))

let <- bind_rows(diary, letFeed) %>% arrange(desc(date))

## Get any new books from Goodreads website

getGoodreads <- function() {
    baseurl <- "https://www.goodreads.com/review/list/5381064?ref=nav_mybooks&page=1"

  rawTab <- read_html(baseurl) %>% 
    html_elements(".bookalike.review")
  
  booksTab <- tibble(
    title = rawTab %>% 
      html_element(".title a") %>% 
      html_text2(),
    author = rawTab %>% 
      html_element('.author a') %>% 
      html_text2(),
    rating = rawTab %>% 
      html_element(".rating .value span") %>% 
      html_attr(name = 'title'),
    ## Think there's a bug where if date is the first of the month, it doesn't show
    date_started_text = rawTab %>% 
      html_element('.date_started_value') %>% 
      html_text2(),
    date_finished_text = rawTab %>% 
      html_element('.date_read_value') %>% 
      html_text2()
  )
  
  cleanTab <- booksTab %>% 
    mutate(rating = case_when(
      rating == 'did not like it' ~ 1,
      rating == 'it was ok' ~ 2,
      rating == 'liked it' ~ 3,
      rating == 'really liked it' ~ 4,
      rating == 'it was amazing' ~ 5
    )) %>% 
    mutate(date_started = ifelse(nchar(date_started_text) == 12,
                                 lubridate::mdy(date_started_text),
                                 lubridate::dmy(str_c("01 ", date_started_text))),
           date_finished = ifelse(nchar(date_finished_text) == 12,
                                  lubridate::mdy(date_finished_text),
                                  lubridate::dmy(str_c("01 ", date_finished_text))),
           .keep = 'unused'
    ) %>% 
    mutate(date_started = as_date(date_started),
           date_finished = as_date(date_finished)) %>% 
    filter()
  
  return(cleanTab)
}

newGoodreads <- getGoodreads()
goodreads <- bind_rows(goodreads, newGoodreads) %>% distinct() %>% 
    arrange(desc(date_finished))
```

Letterboxd
=====================================  

Sidebar {.sidebar data-width=250}
-----------------------------------------------------------------------
  
```{r}
fileInput(inputId = 'uploadFile',
          label = 'Upload new diary.csv file',
          multiple = FALSE, 
          accept = '.csv')
actionButton(inputId = "apply", label = "Apply", icon = icon("play"))

rv <- reactiveValues(let = let)
rv$dropboxToken <- dropboxToken

# reactive({print(head(rv$let))})

observeEvent(eventExpr = input$apply,
             handlerExpr = {
               req(input$uploadFile) 
               print(input$uploadFile$datapath)
               
               newData <- read.csv(input$uploadFile$datapath) %>% 
                 select(title = Name, date = Watched.Date, rating = Rating, tags = Tags) %>% 
                 mutate(date = lubridate::ymd(date)) %>% 
                 arrange(desc(date))
               rv$let <- bind_rows(newData, rv$let %>% 
                                     anti_join(newData, by = c('title', 'date', 'rating')))
               
               file.rename(from = input$uploadFile$datapath, to = 'diary.csv')
               
               reqUpload <- request('https://content.dropboxapi.com/2/files/upload/') %>% 
                   req_oauth_refresh(client = dropboxClient, 
                                     refresh_token = rv$dropboxToken$refresh_token) %>% 
                   req_headers('Content-Type' = 'application/octet-stream') %>% 
                   req_headers(
                       'Dropbox-API-Arg' = str_c('{',
                                          '"autorename":false,',
                                          '"mode":"overwrite",',
                                          '"path":"/R/trakt/letterboxd/diary.csv",',
                                          '"strict_conflict":false', 
                                          '}')
                       ) %>% 
                   req_body_file(path = 'diary.csv')
               
               respUpload <- req_perform(reqUpload)
               
             }, ignoreNULL = FALSE)

```


12m rolling
-----------------------------------------------------------------------
  
### Rolling 12 months
  
```{r}
renderPlotly({
  # plot1 <- rv$let %>%
  plot1 <- let %>%
    select(date, tags) %>% 
    mutate(where = case_when(
      str_detect(tags, 'home') ~ "Home",
      str_detect(tags, 'mv') ~ "Cinema",
      TRUE ~ "Other"
    )) %>% select(-tags) %>% 
    arrange(date) %>% 
    group_by(date, where) %>% count() %>% ungroup() %>% 
    spread(key = where, value = n, fill = 0) %>% 
    mutate(Total = Cinema + Home + Other) %>% 
    select(-Other) %>% 
    
    full_join(data.frame(date = seq.Date(
      from = min(let$date), to = today(), by = 'days'
      # from = min(rv$let$date), to = today(), by = 'days'
    ))) %>% 
    arrange(date) %>% 
    replace_na(list(Cinema = 0, Home = 0, Total = 0)) %>% 
    mutate(
      Cinema = c(cumsum(Cinema[0:364]), zoo::rollsum(Cinema, k = 365, align = 'right')),
      Home = c(cumsum(Home[0:364]), zoo::rollsum(Home, k = 365, align = 'right')),
      Total = c(cumsum(Total[0:364]), zoo::rollsum(Total, k = 365, align = 'right'))) %>% 
    filter(date >= "2012-01-01")
  
  plot_ly() %>% 
    plotly::add_bars(data = let %>%
                       filter(date >= "2012-01-01") %>% 
                       mutate(month = floor_date(date, unit = 'month')) %>% 
                       count(month),
                     name = 'Monthly', x = ~month, y = ~n, 
                     xaxis = 'x', yaxis = 'y', opacity = 0.5,
                     text = ~str_c(format.Date(month, '%b-%y'), ': ', n),
                     hoverinfo = 'text',
                     marker = list(
                       color = "#ffd166")
    ) %>% 
    plotly::add_lines(data = plot1, name = "Rolling 12 months",
                      x = ~date, y = ~Total,
                      line = list(color = "#118ab2"),
                      text = ~str_c(format.Date(date, '%d %b %y'),
                                    ': ', Total), hoverinfo = 'text',
                      xaxis = 'x2', yaxis = 'y2') %>%
    
    plotly::add_lines(data = plot1, name = "Cinema",
                      x = ~date, y = ~Cinema,
                      line = list(color = "#06d6a0"),
                      text = ~str_c(format.Date(date, '%d %b %y'),
                                    ': ', Cinema), hoverinfo = 'text',
                      xaxis = 'x2', yaxis = 'y2') %>%
    
    plotly::add_lines(data = plot1, name = "Home",
                      x = ~date, y = ~Home,
                      line = list(color = "#ef476f"),
                      text = ~str_c(format.Date(date, '%d %b %y'),
                                    ': ', Home), hoverinfo = 'text',
                      xaxis = 'x2', yaxis = 'y2') %>%
    
    plotly::layout(xaxis = list(title = NA),
                   xaxis2 = list(side = 'bottom', overlaying = 'x',
                                 showticklabels = F),
                   yaxis = list(title = NA, side = 'left',
                                overlaying = F),
                   yaxis2 = list(side = 'right', overlaying = 'y',
                                 range = c(0, max(plot1$Total)),
                                 showticklabels = T),
                   legend = list(orientation = 'h'))
})
```

### Where
  
```{r}
renderPlotly({
  plotData <- rv$let %>% 
    # plotData <- let %>% 
    # filter(year(date) == 2010) %>%
    arrange(desc(date)) %>% 
    mutate(rating = rating * 2) %>%
    mutate(where = case_when(
      str_detect(tags, 'home') ~ "Home",
      str_detect(tags, 'mv') ~ "Cinema",
      str_detect(tags, 'plane') ~ "Plane",
      tags == "" ~ "N/A",
      TRUE ~ "Other"
    )) %>%
    mutate(tags = str_remove_all(tags, 'mv'),
           tags = str_remove_all(tags, 'home'),
           tags = str_remove_all(tags, '^, '),
           tags = str_remove_all(tags, ', $'),
           tags = str_replace_all(tags, ', , ', ', ')
    ) %>% 
    mutate(tags = str_to_sentence(tags)) %>% 
    mutate(where = forcats::fct_infreq(where)) %>% 
    group_by(title) %>% 
    arrange(date) %>% 
    mutate(n = row_number()) %>% 
    ungroup() %>% 
    mutate(rewatch = ifelse(
      n == 1, TRUE, FALSE
    ))
  p <- plot_ly(plotData %>% filter(rewatch), 
               x = ~date, y = ~rating, type = 'scatter', mode = 'markers', 
               opacity = 0.6,
               color = ~where, legendgroup = ~where,
               marker = list(size = 25),
               text = ~str_c(title, '<br>', tags), hoverinfo = 'text') %>% 
    add_trace(data = plotData %>% filter(!rewatch),opacity = 0.25,
              x = ~date, y = ~rating, color = ~where, legendgroup = ~where,
              marker = list(size = 25), showlegend = FALSE,
              text = ~title, hoverinfo = 'text')
  p %>% 
    plotly::layout(xaxis = list(title = NA),
                   yaxis = list(title = "Rating"))
})
```

Row
-----------------------------------------------------------------------
  
### Cinema Top 5
  
```{r}
renderPlotly({
  tags <- rv$let %>% 
    filter(str_detect(tags, 'mv')) %>% 
    mutate(tags = str_remove_all(tags, 'mv')) %>% 
    mutate(tags = str_remove_all(tags, '^, '),
           tags = str_remove_all(tags, ', $'),
           tags = str_replace_all(tags, ', , ', ', ')) %>% 
    separate(tags, into = c('1', '2'), sep = ", ") %>% 
    select(-rating) %>% 
    gather(-date, -title, key = key, value = value) %>% 
    filter(!value %in% c('maidavale', 'hampstead', 'bakerstreet', 'screenonthegreen')) %>% 
    mutate(value = str_to_sentence(value)) %>% 
    select(-key) %>% 
    na.omit()
  
  top5 <- tags %>% 
    count(value, sort = T) %>% 
    slice(1:5) %>% 
    pull('value')
  
  mvData <- tags %>% 
    mutate(tags = forcats::fct_other(value, keep = top5, other_level = 'Others')) %>% 
    mutate(date = floor_date(date, unit = 'weeks')) %>% 
    mutate(title = ifelse(tags == 'Others', str_c(title, '<br>', value),
                          title)) %>% 
    select(-value) %>%
    add_count(date, tags) %>% 
    group_by(tags) %>% 
    group_split() %>% 
    map(~full_join(
      x = .,
      y = data.frame(date = seq.Date(from = floor_date(min(tags$date), unit = 'weeks'),
                                     to = today(), by = 'weeks'))
    )) %>% 
    map(arrange, date) %>% 
    map(mutate, n2 = replace_na(n, 0)) %>% 
    map(fill, tags, .direction = 'updown') %>% 
    map(nest, title) %>% 
    map(mutate, cumsum = c(n2[1:51],
                           zoo::rollsum(n2, k = 52, align = 'right'))) %>% 
    map(mutate, smooth = predict(loess(cumsum~as.numeric(date), span = 0.25))) %>% 
    map(unnest, data) %>% 
    map(mutate, smooth = ifelse(smooth < 0, 0, smooth)) %>% 
    map_df(mutate, cumsum = ifelse(is.na(title), NA, cumsum))
  
  plotly::plot_ly(mvData, x = ~as.Date(jitter(as.numeric(date), amount = 25)), type = 'scatter', y = ~cumsum, 
                  mode='markers', color = ~tags, legendgroup = ~tags,
                  marker = list(size = 4, opacity = 0.4), showlegend = FALSE,
                  text = ~ifelse(is.na(title), "", title), hoverinfo = 'text') %>% 
    plotly::add_lines(y = ~smooth, x = ~date, color = ~tags, color = ~tags, mode = 'lines',
                      legendgroup = ~tags, line = list(shape = "spline"),
                      showlegend = TRUE, hoverinfo= 'none') %>% 
    plotly::layout(yaxis = list(title = "Rolling 12 months", tick0 = 0),
                   xaxis = list(title = NA, type='date'))
})
```

### At home Top 5

```{r}
renderPlotly({
  tags <- rv$let %>% 
    filter(str_detect(tags, 'home')) %>% 
    mutate(tags = str_remove_all(tags, 'home')) %>% 
    mutate(tags = str_remove_all(tags, '^, '),
           tags = str_remove_all(tags, ', $'),
           tags = str_replace_all(tags, ', , ', ', ')) %>% 
    select(-rating) %>% 
    gather(-date, -title, key = key, value = value) %>% 
    mutate(value = str_to_sentence(value)) %>% 
    select(-key) %>% 
    na.omit()
  
  top5 <- tags %>% 
    count(value, sort = T) %>% 
    slice(1:5) %>% 
    pull('value')
  
  homeData <- tags %>% 
    mutate(tags = forcats::fct_other(value, keep = top5, other_level = 'Others')) %>% 
    mutate(date = floor_date(date, unit = 'weeks')) %>% 
    mutate(title = ifelse(tags == 'Others', str_c(title, '<br>', value),
                          title)) %>% 
    select(-value) %>%
    add_count(date, tags) %>% 
    group_by(tags) %>% 
    group_split() %>% 
    map(~full_join(
      x = .,
      y = data.frame(date = seq.Date(from = floor_date(min(tags$date), unit = 'weeks'),
                                     to = today(), by = 'weeks'))
    )) %>% 
    map(arrange, date) %>% 
    map(mutate, n2 = replace_na(n, 0)) %>% 
    map(fill, tags, .direction = 'updown') %>% 
    map(nest, title) %>% 
    map(mutate, cumsum = c(n2[1:51],
                           zoo::rollsum(n2, k = 52, align = 'right'))) %>% 
    map(mutate, smooth = predict(loess(cumsum~as.numeric(date), span = 0.25))) %>% 
    map(unnest, data) %>% 
    map(mutate, smooth = ifelse(smooth < 0, 0, smooth)) %>% 
    map_df(mutate, cumsum = ifelse(is.na(title), NA, cumsum))
  
  plotly::plot_ly(homeData, x = ~as.Date(jitter(as.numeric(date), amount = 25)), type = 'scatter', y = ~cumsum, 
                  mode='markers', color = ~tags, legendgroup = ~tags,
                  marker = list(size = 4, opacity = 0.4), showlegend = FALSE,
                  text = ~ifelse(is.na(title), "", title), hoverinfo = 'text') %>% 
    plotly::add_lines(y = ~smooth, x = ~date, color = ~tags, color = ~tags, mode = 'lines',
                      legendgroup = ~tags, line = list(shape = "spline"),
                      showlegend = TRUE, hoverinfo= 'none') %>% 
    plotly::layout(yaxis = list(title = "Rolling 12 months", tick0 = 0),
                   xaxis = list(title = NA, type='date'))
})
```

Goodreads
=====================================  

Sidebar {.sidebar data-width=250}
-----------------------------------------------------------------------

```{r}
actionButton(inputId = 'refreshGoodreads', label = "Refresh", icon('refresh'))
             
rv$goodreads <- goodreads %>% filter(year(date_finished) >= 2011)

# reactive({print(head(rv$let))})

observeEvent(eventExpr = input$refreshGoodreads,
             handlerExpr = {
                 newGoodreads <- getGoodreads()
                 rv$goodreads <- bind_rows(goodreads, newGoodreads) %>% distinct() %>% 
                     arrange(desc(date_finished)) %>% 
                     filter(year(date_finished) >= 2011)
                 
                 write_csv(goodreads, 'goodreads.csv')
                 
                 reqUpload <- request('https://content.dropboxapi.com/2/files/upload/') %>% 
                   req_oauth_refresh(client = dropboxClient, 
                                     refresh_token = rv$dropboxToken$refresh_token) %>% 
                   req_headers('Content-Type' = 'application/octet-stream') %>% 
                   req_headers(
                       'Dropbox-API-Arg' = str_c('{',
                                          '"autorename":false,',
                                          '"mode":"overwrite",',
                                          '"path":"/R/goodreads/goodreads.csv",',
                                          '"strict_conflict":false', 
                                          '}')
                       ) %>% 
                   req_body_file(path = 'goodreads.csv')
               
               respUpload <- req_perform(reqUpload)
               
                 
               }, ignoreNULL = FALSE, ignoreInit = TRUE)


radioButtons(inputId = 'selectGrYear', label = "Select time period",
             choices = c(2011:year(max(goodreads$date_finished, na.rm = T))), 
             selected = year(max(goodreads$date_finished, na.rm=T)))

observeEvent(eventExpr = input$selectGrYear,
             handlerExpr = {
               print(input$selectGrYear)
                 rv$goodreadsC1 <- filter(rv$goodreads, 
                                          year(date_finished) == as.numeric(input$selectGrYear))
                 rv$goodreadsC2 <- rv$goodreadsC1 %>% 
                   arrange(date_finished) %>% 
                   mutate(weekDate = lubridate::floor_date(date_finished, unit = 'weeks')) %>% 
                   count(weekDate) %>% 
                   right_join(data.frame(weekDate = seq.Date(
                     from = floor_date(lubridate::ymd(str_c(as.numeric(input$selectGrYear), "-01-01")), unit = 'weeks'),
                     by = 'weeks', length.out = 52))) %>%
                   arrange(weekDate) %>%
                   mutate(n = replace_na(n, 0)) %>% 
                   mutate(read = cumsum(n)) %>% 
                   mutate(target = row_number()) %>% 
                         mutate(target2 = ifelse(weekDate <= today(), target, NA)) %>% 
                   select(-n) %>% mutate(read = ifelse(weekDate >= lubridate::today(), NA, read)) %>% 
                   gather(-weekDate, key = series, value = count)
                 glimpse(rv$goodreadsC2)
                 })

```

C1 Gantt {data-width=650, data-height = 300}
-----------------------------------------------------------------------
  
### Books finished this year 

```{r}
renderPlot({
  rv$goodreadsC1 %>% 
    filter(!is.na(date_started)) %>% 
    arrange(date_finished) %>% 
    mutate(title = forcats::fct_inorder(title)) %>% 
    # filter(year(date_finished) == 2023) %>% 
    mutate(title = str_sub(title, 1, 36)) %>% 
    ## Plot books started previous year as 1st Jan
    mutate(date_started = ifelse(
      year(date_started) < year(date_finished),
      lubridate::ymd(str_c(year(date_finished), "-01-01")),
      date_started - 1)) %>% 
        
    mutate(date_started= as_date(date_started)) %>% 
    gather(-title, -author, -rating, key = date_type, value = date) %>% 
    ggplot() +
    geom_line(aes(x = fct_rev(fct_inorder(title)), y = date, color = 
                    as.factor(rating)),
            size = 10) + coord_flip() +
    xlab(NULL) + ylab(NULL) + 
    scale_y_date(
      # limits = c(as.Date('2023-01-01', "%Y-%m-%d"), 
      #                     as.Date('2023-12-31', "%Y-%m-%d")),
               date_breaks = '2 months',
               date_labels = '%b',
               expand = c(0,0)) +
    scale_color_discrete(name = 'Rating')

})


```

C2 Cumulative {data-width=650, data-height = 300}
-----------------------------------------------------------------------
  
### Total books reads (target 52)

```{r}
renderPlot({
  rv$goodreadsC2 %>% 
  ggplot(aes(x = weekDate, y = count, color = series, group = series, linetype = series)) +
    geom_line(linewidth = 1.2) +
    scale_color_manual(values = c('read' = '#F8766D', 'target' = '#00BFC4', 'target2' = '#00BFC4'),
                       breaks = c('read', 'target')) +
    # scale_linewidth_manual( values = c(1.2, 0.8, 1.2)) +
    scale_linetype_manual(values = c('read' = 'solid', 'target' = 'dotted', 'target2' = 'solid'),
                          breaks = c('read', 'target')) +
    theme(legend.title = element_blank()) +
    xlab(NULL) + ylab(NULL) +
    theme(text = element_text(size = 16))
})
```


